### ISSUE TITLE
Error recieved after opening Epic Games

### ISSUE THREAD

**Issue by DamianPaniagua** [MasonStooksbury/Free-Games-V2#1]
Upon running Free_Games_V2.py it opens Epic Games and then does nothing. I later clicked the terminal and recieved this error output.

![WindowsTerminal_yZ2OMNhpFz](https://github.com/MasonStooksbury/Free-Games-V2/assets/47050844/38c6e2a5-e47e-4e25-82e1-067556ab47c9)

**Comment by DamianPaniagua** [comment]
I seem to no longer be able to get this to pop up. Now Epic Games just opens, nothing happens for like 10 seconds, and then terminal closes.

**Comment by MasonStooksbury** [comment]
> I seem to no longer be able to get this to pop up. Now Epic Games just opens, nothing happens for like 10 seconds, and then terminal closes.

Hey there! Try downloading the repository as a .zip directory rather than cloning it. I'm using  GitHub's Large File Storage and that means that if you try and clone it you won't get the necessary images you need to make this work.

**Comment by MasonStooksbury** [comment]
Yeah, sorry, this was an oversight on my part. Try redownloading the repository or cloning it.

Long story short (as you mentioned in another issue), I was tracking some necessary files with LFS and that caused it to not send files if you download a ZIP. I've untracked these PNGs since they are small and this issue should be fixed
