### ISSUE TITLE
Not passing "mature content" screen

### ISSUE THREAD

**Issue by DamianPaniagua** [MasonStooksbury/Free-Games-V2#3]
(Thank you for fixing other issues swiftly!)

Upon running "Free_Games_V2.py" It proceeds perfectly until hitting the mature content screen.

I may be wrong but this may be due to updated or just differing UI styles for users?

Here is a picture of what "continue_button.png" looks like versus my UI.

![EpicGamesLauncher_uPz0121Hk3](https://github.com/MasonStooksbury/Free-Games-V2/assets/47050844/011ae2a8-751e-4e3c-9d9a-4d04b81e0bcb)

**Comment by MasonStooksbury** [comment]
No problem! 

So, the way template matching works is that OpenCV only matches what you provide it. I chose not to grab the entire button or area for most things because of what you mentioned. Different styles and sizes might mess it up. So here, it really only needs the small portion that says "Continue" in order to be able to find it. It also converts things to grayscale before looking so the color shouldn't matter either. Let me test this and see if I can get a fix out soon

Thanks again for making an issue!

**Comment by DamianPaniagua** [comment]
Hey, I was able to fix it myself by using ShareX to capture the button with my styling but using the exact amount of pixels and then replacing the original "continue_button.png" image. 

I replaced it using this image and now everything worked perfectly. Thank you.

![continue_button](https://github.com/MasonStooksbury/Free-Games-V2/assets/47050844/97b4f91f-66ce-49a9-9567-c991e056726a)

**Comment by DamianPaniagua** [comment]
(Deleted last comment think I put wrong file)

Hey, I was able to fix it myself by using ShareX to capture the button with my styling but using the exact amount of pixels and then replacing the original "continue_button.png" image.

I replaced it using this image and now everything worked perfectly. Thank you.

![continue_button](https://github.com/MasonStooksbury/Free-Games-V2/assets/47050844/0da19c49-9613-4782-bdbd-96560a38c917)

**Comment by MasonStooksbury** [comment]
> (Deleted last comment think I put wrong file)
> 
> Hey, I was able to fix it myself by using ShareX to capture the button with my styling but using the exact amount of pixels and then replacing the original "continue_button.png" image.
> 
> I replaced it using this image and now everything worked perfectly. Thank you.
> 
> ![continue_button](https://private-user-images.githubusercontent.com/47050844/293513012-0da19c49-9613-4782-bdbd-96560a38c917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzc2MTYsIm5iZiI6MTcwNDAzNzMxNiwicGF0aCI6Ii80NzA1MDg0NC8yOTM1MTMwMTItMGRhMTljNDktOTYxMy00NzgyLWJkYmQtOTY1NjBhMzhjOTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1NDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExOTQ4ZjBjM2QxZDhhNTkzNjZhYTBjMmU1NGIzZWU2YWUwZDY3NzA2MDNhMmVjYzEwMjg5Y2U2NTE4MWU5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mgHGSH803OmuU5ic6-AZa6m-M6e-mBwwjcHyT5alTrQ)

Nice fix!

I think I'm going to play around with doing a bit of fuzzy matching or something so you shouldn't have to do that. It might be a bit too precise at the moment and so different size monitors or resolutions might be giving it some issue

**Comment by DamianPaniagua** [comment]
Now that I think of it I am probably a niche case haha. I am using 1440p monitors but also using remote desktop to run this on my second computer. So very possible my UI is unique.

**Comment by MasonStooksbury** [comment]
For some reason my own image didn't work when I tried it today lol I retook the image and tried that without issue. Also modified how the template matching works to make it a bit fuzzier so that hopefully any differences in resolution/font won't matter as much. But, frankly, this one is a little hard to accurately test so it very well could break again :/
